# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Parse version from tag
      id: version
      uses: release-kit/semver@v1

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          -Pversion=${{ steps.version.outputs.full }}
          publish
      env:
        REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
        REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
