name: Gradle Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'corretto'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build

    - name: Parse version from tag
      id: version
      uses: release-kit/semver@v2

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v3
      with:
        arguments: |
          -Pversion=${{ steps.version.outputs.full }}
          publish
      env:
        REPOSILITE_USERNAME: ${{ secrets.REPOSILITE_USERNAME }}
        REPOSILITE_PASSWORD: ${{ secrets.REPOSILITE_PASSWORD }}
